### ISSUE TITLE
Error 405 : message=Method Not Allowed

### ISSUE THREAD

**Issue by asenawritescode** [asenawritescode/TinypesaRetrofitApp#1]
Response{protocol=http/1.0, code=405, message=Method Not Allowed, url=https://tinypesa.com/api/v1/express/initialize}
 
 I have confirmed the URL is correct and it accepts the headers required.
 
## Tiny pesa doc link https://tinypesa.com/developers/docs/1.0/stk

**Comment by kariuki-joseph** [comment]
Got your issue. Could you have tested the endpoint via Postman maybe?

**Comment by kariuki-joseph** [comment]
I shall make a pull request once I have resolved the issue

**Comment by asenawritescode** [comment]
I have been using the API. 
Yes it works

**Comment by asenawritescode** [comment]
Issue was resolved !
